import{useMemo,useState}from'react';import{createDigest,digestMarkdown,type Status,type Update}from'./domain/digest';import AiMode from'./AiMode';
const sample:Update[]=[{id:1,name:'Nora',role:'Product design',status:'On track',progress:'Validated the new onboarding flow with five internal users.',next:'Prepare the responsive handoff and edge states.',blocker:'',decision:'Confirm whether analytics consent appears before account creation.'},{id:2,name:'Leo',role:'Engineering',status:'At risk',progress:'Completed the workflow API and validation rules.',next:'Connect the staging environment and finish error handling.',blocker:'Staging credentials are still pending from the client IT team.',decision:''},{id:3,name:'Samira',role:'Growth',status:'On track',progress:'Finalized the launch message and partner email sequence.',next:'Build the campaign segments and UTM plan.',blocker:'',decision:'Approve the launch audience by Thursday.'}];
const blank=(id:number):Update=>({id,name:'New teammate',role:'Role',status:'On track',progress:'',next:'',blocker:'',decision:''});
function App(){const[team,setTeam]=useState('Orbit launch team');const[updates,setUpdates]=useState<Update[]>(sample);const[active,setActive]=useState(1);const[copied,setCopied]=useState(false);const digest=useMemo(()=>createDigest(updates),[updates]);const edit=(id:number,key:keyof Update,value:string)=>setUpdates(xs=>xs.map(x=>x.id===id?{...x,[key]:value}:x));const add=()=>{const id=Math.max(0,...updates.map(x=>x.id))+1;setUpdates(x=>[...x,blank(id)]);setActive(id)};const remove=(id:number)=>{const next=updates.filter(x=>x.id!==id);setUpdates(next);if(active===id)setActive(next[0]?.id??0)};const restore=()=>{setUpdates(sample);setActive(sample[0].id)};async function copy(){await navigator.clipboard.writeText(digestMarkdown(team,updates));setCopied(true);setTimeout(()=>setCopied(false),1800)}return <main>
<nav><a href="#top"><b>D</b> DISPATCH</a><span>TEAM INTELLIGENCE / 06</span><button onClick={restore}>Restore sample</button></nav>
<header id="top"><p>Less status theatre. More shared direction.</p><h1>Turn updates into<br/><em>leadership clarity.</em></h1><div className="edition"><span>ISSUE</span><strong>06</strong><small>{new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</small></div></header>
<AiMode app="team-update-digest" payload={{team,updates,localResult:digest}} label="Create leadership digest with AI"/>
<section className="board"><aside className="roster"><div className="roster-head"><label>Team<input value={team} onChange={e=>setTeam(e.target.value)}/></label><button onClick={add}>+</button></div>{updates.map((u,i)=><button className={`person ${active===u.id?'active':''}`} onClick={()=>setActive(u.id)} key={u.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{u.name}</b><small>{u.role}</small></div><i className={u.status.toLowerCase().replace(' ','-')}/></button>)}<div className="status-key"><span><i className="on-track"/> On track</span><span><i className="at-risk"/> At risk</span><span><i className="blocked"/> Blocked</span></div></aside>
<div className="editor">{updates.filter(x=>x.id===active).map(u=><div key={u.id}><div className="editor-head"><div><span>Update from</span><input value={u.name} onChange={e=>edit(u.id,'name',e.target.value)}/><input className="role" value={u.role} onChange={e=>edit(u.id,'role',e.target.value)}/></div><label>Status<select value={u.status} onChange={e=>edit(u.id,'status',e.target.value as Status)}><option>On track</option><option>At risk</option><option>Blocked</option></select></label></div><label className="prompt"><span><b>01</b>What moved forward?</span><textarea value={u.progress} onChange={e=>edit(u.id,'progress',e.target.value)} placeholder="Completed work, evidence, or learning…"/></label><label className="prompt"><span><b>02</b>What happens next?</span><textarea value={u.next} onChange={e=>edit(u.id,'next',e.target.value)} placeholder="The next meaningful move…"/></label><div className="two"><label className="prompt"><span><b>03</b>What is blocked?</span><textarea value={u.blocker} onChange={e=>edit(u.id,'blocker',e.target.value)} placeholder="Dependency, owner, or constraint…"/></label><label className="prompt"><span><b>04</b>Decision needed?</span><textarea value={u.decision} onChange={e=>edit(u.id,'decision',e.target.value)} placeholder="The decision and deadline…"/></label></div><button className="delete" onClick={()=>remove(u.id)}>Remove update</button></div>)}</div>
<aside className="digest"><div className="digest-head"><span>Live leadership brief</span><div><b>{digest.onTrack.length}</b><small>on track</small><b>{digest.atRisk.length+digest.blocked.length}</b><small>need attention</small></div></div><section><h2>Momentum</h2>{digest.progress.map(x=><p key={x}>{x}</p>)}</section><section className={digest.blockers.length?'attention':''}><h2>Blockers</h2>{digest.blockers.length?digest.blockers.map(x=><p key={x}>{x}</p>):<p>No blockers reported.</p>}</section><section><h2>Decisions</h2>{digest.decisions.length?digest.decisions.map(x=><p key={x}>{x}</p>):<p>No decisions requested.</p>}</section><section><h2>Next moves</h2>{digest.next.map(x=><p key={x}>{x}</p>)}</section><button onClick={copy}>{copied?'Digest copied':'Copy digest ↗'}</button></aside></section>
<footer><span>Built by Jamil Darwish</span><span>Local workspace · No employee data uploaded</span></footer></main>}
export default App;
